### ISSUE TITLE
feat: GlobalNavigationBar 모든 페이지 적용, px값 수정

### ISSUE THREAD

**Issue by YongChanCho** [KUIT-MAPU/MAPU-Frontend#23]
## 📌 목적 / 이슈 내용
내용
GlobalNavigationbar 모든 페이지 적용, px 값 수정

<br>

## 📝 상세 내용
- 내용
GlobalNavigationbar 모든 페이지 적용, px 값 수정

<br>

## ✔ 체크 리스트
- [x] 내용

<br>

## 💡 비고
- (참고 사항 및 레퍼런스)
- 내용

**Comment by ro-el-c** [comment]
어떤 px 값 수정하는지도 써주시는게 이해가 쉬울 것 같습니다
